name: Publish Website

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'

    - name: Install MkDocs and plugins
      run: |
        pip install mkdocs mkdocs-material mkdocs-minify-plugin

    - name: Build MkDocs site
      run: mkdocs build

    - name: Upload built site
      uses: actions/upload-artifact@v3
      with:
        name: zjoule-website
        path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: zjoule-website

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.NEFARIOUS_PERSONAL_TOKEN }}
        publish_dir: ./zjoule-website